# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1872R8cDKTJR8YDcGmQj7LmDlnqv_0WFD
"""

import pandas as pd

# Create the data as a dictionary
data = {
    'CustomerID': ['C0055', 'C0157', 'C0069'],
    'Region': ['North America', 'North America', 'Europe'],
    'total_spend': [-0.333486, -0.870435, -0.321993]
}

# Create a pandas DataFrame
df = pd.DataFrame(data)

# Save the DataFrame to a CSV file
df.to_csv('customer_data.csv', index=False)

# Print the DataFrame (optional) to verify
print(df)